[project]
name = "reader-app"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Ciastelix", email = "tenlegitmati@gmail.com"},
]
dependencies = []
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
