from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "ada213071b71"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # No operations needed as the column already exists
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("description")
    # ### end Alembic commands ###
